# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-downloads-extension}
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["spanner"]
  s.date = %q{2010-10-20}
  s.description = %q{Controlled, secure file access with group-based access control.}
  s.email = %q{will@spanner.org}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/downloads_controller.rb",
     "app/controllers/downloads_controller.rb",
     "app/models/download.rb",
     "app/views/admin/downloads/_form.html.haml",
     "app/views/admin/downloads/edit.html.haml",
     "app/views/admin/downloads/index.html.haml",
     "app/views/admin/downloads/new.html.haml",
     "config/routes.rb",
     "db/migrate/001_create_downloads.rb",
     "downloads_extension.rb",
     "lib/download_group.rb",
     "lib/download_tags.rb",
     "lib/download_ui.rb",
     "lib/tasks/downloads_extension_tasks.rake",
     "public/stylesheets/admin/downloads.css",
     "radiant-downloads-extension.gemspec",
     "spec/controllers/downloads_controller_spec.rb",
     "spec/datasets/download_groups_dataset.rb",
     "spec/datasets/download_readers_dataset.rb",
     "spec/datasets/download_sites_dataset.rb",
     "spec/datasets/downloads_dataset.rb",
     "spec/files/test.pdf",
     "spec/files/test.txt",
     "spec/models/download_spec.rb",
     "spec/models/group_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/spanner/radiant-downloads-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Controlled, secure file access for Radiant CMS with group-based access control.}
  s.test_files = [
    "spec/controllers/downloads_controller_spec.rb",
     "spec/datasets/download_groups_dataset.rb",
     "spec/datasets/download_readers_dataset.rb",
     "spec/datasets/download_sites_dataset.rb",
     "spec/datasets/downloads_dataset.rb",
     "spec/models/download_spec.rb",
     "spec/models/group_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<radiant-reader_group-extension>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
    else
      s.add_dependency(%q<radiant>, [">= 0.9.0"])
      s.add_dependency(%q<radiant-reader_group-extension>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0.9.0"])
    s.add_dependency(%q<radiant-reader_group-extension>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
  end
end

